### ISSUE TITLE
Optionally use TLS for Kombu Connection to RabbitMQ

### ISSUE THREAD

**Issue by milescrabill** [mozilla-services/elmo-automation#3]
At present our Kombu connection to RabbitMQ is created as follows:

`Connection(settings.TRANSPORT)` which configures the connection without TLS. According to [this](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.connection.html), it should be as simple as optionally setting `ssl=True` in the instantiation. It might be good to get an env var to separate that out between the environments.

**Comment by milescrabill** [comment]
For now I've just changed our RabbitMQ ELB to accept TCP w/o SSL.

**Comment by Pike** [comment]
Moved to [bug 1453931](https://bugzilla.mozilla.org/show_bug.cgi?id=1453931).
